version: "3"
services:
  nginx:
    image: 'nginx'
    labels:
      - traefik.backend=nginx
      - traefik.frontend.rule=Host:nua.media,www.nua.media
      - traefik.docker.network=proxy
      - traefik.port=80
    networks:
      - internal
      - proxy
  caddy:
    image: 'abiosoft/caddy'
    labels:
      - traefik.backend=caddy
      - traefik.frontend.rule=Host:nua.co,www.nua.co
      - traefik.docker.network=proxy
      - traefik.port=2015
    networks:
      - internal
      - proxy

networks:
  proxy:
    external: true
  internal:
    external: false
