version: "3"
services:
  wwwnua:
    image: 'emilevauge/whoami'
    labels:
      - "traefik.backend=wwwnua"
      - "traefik.frontend.rule=Host:www.nua.co,nua.co"
    volumes:
      # - ./Caddyfile:/etc/Caddyfile
      # - ./site1:/srv/webapp/current/public
    networks:
      - internal
      - proxy
  nginx:
    image: 'nginx'
    labels:
      - "traefik.backend=nginx"
      - "traefik.frontend.rule=Host:www.nua.media,nua.media"
      - "traefik.docker.network=proxy"
      - "traefik.port=80"
    networks:
      - internal
      - proxy
networks:
  proxy:
    external: true
  internal:
    external: false
