version: "3"
services:
  caddy2:
    image: 'abiosoft/caddy'
    labels:
      - "traefik.backend=caddy2"
      - "traefik.frontend.rule=Host:www.nua.media,nua.media"
      - "traefik.docker.network=proxy"
      - "traefik.port=2015"
    networks:
      - internal
      - proxy
  caddy:
    image: 'abiosoft/caddy'
    labels:
      - "traefik.backend=caddy"
      - "traefik.frontend.rule=Host:www.nua.co,nua.co"
      - "traefik.docker.network=proxy"
      - "traefik.port=2015"
    networks:
      - internal
      - proxy
  whoami:
    image: emilevauge/whoami
    networks:
      - internal
      - proxy
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:www.sononix.com,sononix.com"

networks:
  proxy:
    external: true
  internal:
    external: false
