version: "3"
services:
  caddy:
    image: 'abiosoft/caddy'
    labels:
      - "traefik.backend=caddy"
      - "traefik.frontend.rule=Host:www.nua.media,nua.media"
      - "traefik.docker.network=proxy"
      - "traefik.port=2015"
      - "traefik.port=443"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./site1:/srv/webapp/current/public
    ports:
      - "80:80"
      - "443:443"
      - "2015:2015"
    networks:
      - internal
      - proxy
networks:
  proxy:
    external: true
  internal:
    external: false
