version: "3"
services:

  whoami:
    image: emilevauge/whoami
    networks:
      - internal
      - proxy
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:www.nua.co,nua.co"

networks:
  proxy:
    external: true
  internal:
    external: false
