version: "3"
services:
  nginx:
    image: 'nginx'
    labels:
      - "traefik.backend=nginx"
      - "traefik.frontend.rule=Host:nua.media,blog.nua.media"
      - "traefik.docker.network=proxy"
      - "traefik.port=80"
    networks:
      - internal
      - proxy
  caddy:
    image: 'abiosoft/caddy'
    labels:
      - "traefik.backend=caddy"
      - "traefik.frontend.rule=Host:nua.co,blog.nua.co"
      - "traefik.docker.network=proxy"
      - "traefik.port=2015"
    networks:
      - internal
      - proxy
  whoami:
    image: emilevauge/whoami
    networks:
      - internal
      - proxy
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:www.sononix.com,sononix.com"

networks:
  proxy:
    external: true
  internal:
    external: false
