version: '3'
services:
  lb:
    image: traefik:latest
    command: >
      --web --docker --docker.swarmmode
      --docker.domain=traefik --docker.watch
      --accesslogsfile=/dev/stdout --logLevel=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    ports:
      - "9000:80"
      - "9001:8080"
    deploy:
      placement:
        constraints:
          - node.role == manager

  nginx:
    image: 'nginx'
    deploy:
      labels:
        - "traefik.frontend.rule=PathPrefix:/"
        - "traefik.backend=nginx"
        - "traefik.port=80"
        - "traefik.weight=5"

  helloworld:
    image: dockercloud/hello-world
    deploy:
      labels:
        - "traefik.frontend.rule=PathPrefix:/hello/"
        - "traefik.backend=hello"
        - "traefik.port=80"
        - "traefik.weight=7"
