version: "3"
services:
  nginx:
    image: 'nginx'
    labels:
      - traefik.backend=blog
      - traefik.frontend.rule=Host:blog.example.com
      - traefik.docker.network=proxy
      - traefik.port=80
    networks:
      - internal
      - proxy

networks:
  proxy:
    external: true
  internal:
    external: false
