version: "3"
services:
  caddyhttps:
    image: 'abiosoft/caddy'
    labels:
      - "traefik.backend=caddyhttps"
      - "traefik.frontend.rule=Host:www.nua.co,nua.co"
      - "traefik.docker.network=proxy"
      - "traefik.port=2015"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./site1:/srv/webapp/current/public
    networks:
      - internal
      - proxy

networks:
  proxy:
    external: true
  internal:
    external: false
